/*
 * Author: Stefan Zajicek
 * zajicekx@gmail.com
 * more info https://github.com/zajicek/simpleFormStorage
 */
function generateFormDataSFS(b) { var c = b; if (null == b || 0 < b.length) c = {}; b = getAllElementsWithAttribute("savedata", "true"); for (i = 0; i < b.length; i++) { var a = b[i].getAttribute("savedataId"); c[a] = {}; "checkbox" == b[i].getAttribute("type") ? c[a].value = b[i].checked : c[a].value = b[i].value } return JSON.stringify(c) } function saveDataSFS(b, c) { setCookie("formData", b, c) } function loadFormDataSFS() { var b = getCookie("formData"); return null == b ? null : JSON.parse(b) }
function fillInputsSFS(b) { if (null != b) for (var c in b) if (b.hasOwnProperty(c)) { var a = document.querySelectorAll("[savedataId='" + c + "']")[0]; void 0 != a && ("SELECT" == a.tagName.toUpperCase() ? a.value = b[c].value : "" == a.value || null == a.value ? void 0 != a.attributes.type.value && "INPUT" == a.tagName.toUpperCase() && "CHECKBOX" != a.attributes.type.value.toUpperCase() && (a.value = b[c].value) : void 0 != a.attributes.type && "CHECKBOX" == a.attributes.type.value.toUpperCase() && (a.checked = b[c].value ? !0 : !1)) } }
function getAllElementsWithAttribute(b, c) { for (var a = [], d = document.getElementsByTagName("*"), e = 0, f = d.length; e < f; e++) d[e].getAttribute(b) == c && a.push(d[e]); return a } function setCookie(b, c, a) { var d = new Date; d.setTime(d.getTime() + 864E5 * a); a = "expires=" + d.toUTCString(); document.cookie = b + "=" + c + ";" + a + ";path=/" }
function getCookie(b) { b += "="; for (var c = document.cookie.split(";"), a = 0; a < c.length; a++) { for (var d = c[a]; " " == d.charAt(0) ;) d = d.substring(1); if (0 == d.indexOf(b)) return d.substring(b.length, d.length) } return null }
function initSFS(b) { var c = loadFormDataSFS(); fillInputsSFS(c); document.addEventListener("input", function (a) { void 0 != a.target.attributes.savedata && "true" == a.target.attributes.savedata.value && saveDataSFS(generateFormDataSFS(loadFormDataSFS()), b) }); document.addEventListener("change", function (a) { void 0 != a.target.attributes.savedata && "true" == a.target.attributes.savedata.value && saveDataSFS(generateFormDataSFS(loadFormDataSFS()), b) }) };
